// Account endpoints for the app: profile, push devices, password reset, delete. Same setup as payments.test.mjs.
import postgres from "postgres";
import { createHash } from "crypto";
const APP = "http://localhost:3000/api/v1";
const sql = postgres(process.env.DATABASE_URL);
let token = "", pass = 0, failN = 0;
const ok = (c, m, x) => { if (c) { pass++; console.log("  ✓", m); } else { failN++; console.log("  ✗", m, x !== undefined ? JSON.stringify(x).slice(0, 300) : ""); } };
const api = async (path, body, method) => {
  const r = await fetch(APP + path, { method: method || (body ? "POST" : "GET"), headers: { "content-type": "application/json", "x-forwarded-for": "10.1.0." + Math.floor(Math.random() * 250), ...(token ? { authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
  return { status: r.status, ...(await r.json().catch(() => ({}))) };
};
const email = `acct${Date.now()}@example.com`;
const reg = await api("/auth/register", { name: "Bola Ade", email, password: "password123" });
token = reg.token;
ok(reg.user, "registered", reg);
const p = await api("/me", { name: "Bola Adeyemi", phone: "0803 555 1234" }, "PATCH");
ok(p.user?.name === "Bola Adeyemi" && p.user?.phone === "+2348035551234", "profile edited", p);
const bad = await api("/me", { phone: "123" }, "PATCH");
ok(bad.status === 400 && bad.fields?.phone, "bad phone refused", bad);
const dev = await api("/me/devices", { token: "ExponentPushToken[abcDEF123456789xyz]", platform: "ios" });
ok(dev.ok, "push token saved", dev);
ok((await api("/me/devices", { token: "nope" })).status === 400, "junk token refused");
const [d] = await sql`select user_id from devices where token = 'ExponentPushToken[abcDEF123456789xyz]'`;
ok(d?.user_id === reg.user.id, "device linked to user");
ok((await api("/auth/apple", { identityToken: "x.y.z" })).status === 401, "bad Apple token refused");
// Reset: same answer for unknown emails; then use a known code.
const r0 = await api("/auth/reset", { email: "nobody@example.com" });
ok(r0.ok, "unknown email gets the same answer");
const r1 = await api("/auth/reset", { email });
ok(r1.ok, "reset started");
await sql`update password_resets set code_hash = ${createHash("sha256").update(`${reg.user.id}:123456`).digest("hex")} where user_id = ${reg.user.id}`;
const wrong = await api("/auth/reset/confirm", { email, code: "000000", password: "newpassword1" });
ok(wrong.status === 400, "wrong code refused", wrong);
const right = await api("/auth/reset/confirm", { email, code: "123 456", password: "newpassword1" });
ok(right.token, "right code sets password", right);
const login = await api("/auth/login", { email, password: "newpassword1" });
ok(login.token, "signs in with new password");
token = login.token;
ok((await api("/me", {}, "DELETE")).status === 400, "delete needs confirm");
const del = await api("/me", { confirm: "DELETE" }, "DELETE");
ok(del.ok, "account deleted", del);
ok((await api("/me/orders")).status === 401, "old token no longer works");
ok((await api("/auth/login", { email, password: "newpassword1" })).status === 401, "can't sign in after delete");
const [u] = await sql`select email, name, deleted_at from users where id = ${reg.user.id}`;
const [dv] = await sql`select count(*)::int n from devices where user_id = ${reg.user.id}`;
ok(u.email.startsWith("deleted+") && u.name === "" && u.deleted_at && dv.n === 0, "details removed, devices gone", u);
const again = await api("/auth/register", { name: "Bola Ade", email, password: "password123" });
ok(again.token, "same email can register again");
console.log(`\n${pass} passed, ${failN} failed`);
await sql.end();
process.exit(failN ? 1 : 0);
